### PR TITLE
Fixed request data format to get a valid response from Netflix again

### PR DESCRIPTION
**Pull request by xLAva**
Fixed list fetch from Netflix
* changed http request data format

Fixed issue "Plug-in no longer functioning." #640

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [x ] Have you followed the guidelines in our Contributing document?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ x] Have you successfully ran tests with your changes locally?

## Screenshots (if appropriate):

[You can erase any parts of this template not applicable to your Pull Request.]

### CODE REVIEW

**Comment by ctatos** [comment]
Great work! Thank you!

**Comment by liberty-developer** [comment]
Very cool, thx! Will merge and bump a version

**Comment by CastagnaIT** [comment]
this commit changes the format of the request but you forgot to correct the header, this way you make wrong requests the server may one day refuse them

**Comment by budafuko** [comment]
thank you works great. what about 0.14? gonna be fixed?

**Comment by enrique131** [comment]
This is not working for me. trying to log in after update gives me lolomo error
tried the last 3 updates
1.0.0
1.1.0
1.1.1
0.14 was the last one that worked for me since last week that i updated to 1.0.0.
i cant see how it was fixed here... or understand how you did it

**Pull request merged**
