### PR TITLE
Exportfolder for Main Menu

### PR DESCRIPTION
**Pull request by hawkeyexp**
Add folder "Exported" to main menu to give the user easy access to his exported media from netflix.  By selecting an item a dialog opens which asks for delete item. If yes it will remove exported media from db and export folder.
In this state an error will happen when media is not part if local db (possible caused by exporting from multiple clients). I will add a function to rebuild local db from exported stuff to fix it in next updates.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Using 85c1543bf7bd6f1a875a3ae12c2af4811bdb7752

Clicking on "Exported"

s1

results in an exception:

```
16:27:41.044 T:1669706640   DEBUG: [Netflix] "Navigation::before_routing_action" returned: {'main_menu_selection': 'exported'}
16:27:41.053 T:1669706640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'movies' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 37, in <module>
                                                navigation.router(paramstring=sys.argv[2][1:])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 27, in wrapped
                                                result = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 137, in router
                                                return self.kodi_helper.build_video_listing_exported(content=self.library.list_exported_media(),build_url=self.build_url)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/Library.py", line 599, in list_exported_media
                                                return movies+shows
                                            UnboundLocalError: local variable 'movies' referenced before assignment
                                            -->End of Python script error report<--
```

Full log: http://sprunge.us/bafL

**Comment by asciidisco** [comment]
@MilhouseVH Have you picked that PR yourself? I haven't merged it because @hawkeyexp added another one which made this one obsolete & I´ve merged that into master a couple of hours ago.

https://github.com/asciidisco/plugin.video.netflix/pull/139

**Comment by MilhouseVH** [comment]
My apologies - I shouldn't have posted on this PR, will continue conversation in #139.

**Comment by asciidisco** [comment]
@MilhouseVH No worries, I just wanted to double check that you haven't used the wrong branch, finding is very legitimate. Thanks 👍

**Pull request closed without merging**
