### PR TITLE
additional informations for listitems

### PR DESCRIPTION
**Pull request by Maven85**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
ff2b5ac70453c86580956b4e0f6b16bb514c9566 is fine, but 18b02a6447156d449d549a8a5d95bd10ab9b680d results in the following error when accessing "Netflix originals" (Kids shows):

http://sprunge.us/iOBR

Normally I would expect to see this listing:
s1

but now with 18b02a6447156d449d549a8a5d95bd10ab9b680d only the error in the log.,

Possibly the "2" in Project Mc2 is not being handled (decoded) correctly?

s2

**Comment by MilhouseVH** [comment]
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 10: ordinal not in range(128)
```
Yep, `u'\xb2'` is "superscript 2": http://www.charbase.com/00b2-unicode-superscript-two

Debug log of the error: http://sprunge.us/IPce (if it helps)

**Comment by asciidisco** [comment]
@MilhouseVH Thank you for reporting & investigating. I haven't had the time to properly test this PR (Pen test looked fine). Will fix the encoding issues before the next release.

**Comment by asciidisco** [comment]
@MilhouseVH I´ve applied patches to the master branch that *should* fix this. I´m currently on vacation & have limited test equipment with me (well, more like zero to none). If you´ve some time to retest this, it would be highly appreciated. Thanks again.

**Comment by MilhouseVH** [comment]
Hi @asciidisco yes, that fixes the issue - many thanks!

**Comment by asciidisco** [comment]
@MilhouseVH Thank you for the heads up & testing, I´ve just drafted a new release 0.11.19n with the changes

**Comment by troych** [comment]
Is it possible that this breaks the abillity to play back .strm files created by the "Export to Library" function in the netflix addon?

```
14:54:54.623 T:140230744868608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('infoLabels',)
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 37, in <module>
                                                navigation.router(paramstring=sys.argv[2][1:])
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 27, in wrapped
                                                result = f(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 109, in router
                                                self.play_video(video_id=params['video_id'], start_offset=params.get('start_offset', -1), infoLabels=params['infoLabels'])
                                            KeyError: ('infoLabels',)
                                            -->End of Python script error report<--
```

This is what I get when I try to play back a .strm file, if I replace the 2 files that got changed in this commit I can playback .strm files again.

**Comment by Maven85** [comment]
Your're right.

A Fix is on the way.
#88

**Pull request merged**
