### PR TITLE
add pycryptodomex to dependencies

### PR DESCRIPTION
**Pull request by guss77**
As per the discussion in issue #30 ( https://github.com/asciidisco/plugin.video.netflix/issues/30 )

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you successfully ran tests with your changes locally?

## Screenshots (if appropriate):

[You can erase any parts of this template not applicable to your Pull Request.]

### CODE REVIEW

**Comment by Mattia98** [comment]
It took me way to long to figure out that I needed that pip package. Adding this to the guide is crucial!!

**Comment by LtFeroX** [comment]
@Mattia98 can you tell me how you installed it ? Thx

**Comment by Teods** [comment]
@LtFeroX Just like in the modified Readme just use `pip install --user pycryptodomex` in your terminal to install it and run netflix addon.

This PR is really needed in the installation guide.

**Comment by montvid** [comment]
Yes, I needed it too for ubuntu. Please add this pr.

**Comment by montvid** [comment]
I still need to install pip install --user pycryptodomex in order for netflix plugin to load to login screen. Is there a fix or maybe add to install instructions this command?

**Pull request merged**
