### PR TITLE
Update NetflixSession.py

### PR DESCRIPTION
**Pull request by urbanboy**
This change allows shows episodes by season that contains a lot of episodes for example > 42

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully ran tests with your changes locally?

## Screenshots (if appropriate):

[You can erase any parts of this template not applicable to your Pull Request.]

### CODE REVIEW

**Comment by urbanboy** [comment]
changing the follow number 40 in the line 
def fetch_episodes_by_season(self, season_id, list_from=-1, list_to=40):
allow shows more than 42 episodes by season for Series that have more episodes than 42 by season
def fetch_episodes_by_season(self, season_id, list_from=-1, list_to=500):

**Comment by liberty-developer** [comment]
Intention of this addon is acting same as Netflix webpage / addon.
Can you pls. tell us a season with > 40 entries? Want to validate how Netflix is handling this.

**Comment by asciidisco** [comment]
Your change won’t work, you can fetch max 27 entries per fetch & only if you do not fetch all information. Multiple requests are needed to fetch lists with more entries, the patent list tells us the number of entries available, but to integrate this in a way that it makes sense in term of loading time, we’d need to integrate multi threaded parallel requests. It’s possible but rather hard to implement.

**Comment by urbanboy** [comment]
Thanks You for the replies , a Lot of latinoamerican tv shows have >40 entries by season  for example the tv show "la seleccion", in addition changing  these lines fix the issue https://github.com/asciidisco/plugin.video.netflix/issues/288.

**Comment by caphm** [comment]
Closing, as this requires a more elaborate implementation.

**Comment by simonbuehler** [comment]
pokemon indigo league is an example

**Pull request closed without merging**
