### PR TITLE
Implement inputstreamhelper

### PR DESCRIPTION
**Pull request by emilsvennesson**
## Types of changes

* Displays informative dialogs if required InputStream components are unavailable
* Automatically installs Widevine CDM on supported platforms
  * Keeps Widevine CDM up-to-date with the latest version available
  * Checks for missing depending libraries by parsing the output from  `ldd`

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change

### CODE REVIEW

**Comment by corna** [comment]
Note that the latest version of libwidevine is broken on the Raspberry Pi, this PR should be put on hold until a fix is available.

[Here's](https://github.com/Sandmann79/xbmc/issues/62) the report and [here](https://www.kodinerds.net/index.php/Thread/44211-Release-Amazon-Prime-Instant-Video/?postID=441015#post441015) the explanation.

Google Translate: "The new libwidevine now decodes the YUV images differently (UV are juxtaposed instead of one above the other).
The kodi internal GL / GLES renderer recognizes what the reason is that it is going on Odroid. RBPI (uses its own h / w renderer) can indeed do that, but needs a) a bit of development and b.) A new firmware. Something will come in the next few days."

**Comment by emilsvennesson** [comment]
@corna This has been fixed in the latest Milhouse builds.

https://forum.kodi.tv/showthread.php?tid=298461&pid=2701351#pid2701351

**Comment by corna** [comment]
Both Netflix (this plugin) and Amazon Prime Video ([plugin.video.amazon-test](https://github.com/Sandmann79/xbmc)) work with the latest libwidevine downloaded by inputstreamhelper from the latest Chrome recovery image on a RPi 3.

**Comment by hawkeyexp** [comment]
I can confirm - latest libwidevine working fine.

**Pull request merged**
