### PR TITLE
Add locale support

### PR DESCRIPTION
**Pull request by GTechAlpha**
Should fix issue #202 and may help with general playback for some.
The included locale list is fairly comprehensive; I do not know exactly which ones are or are not supported by NX.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

### All Submissions:

* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [X] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by asciidisco** [comment]
Nice. Maybe we could get rid of the big language map file & some other boilerplate using:
[xbmc.convertLanguage](http://romanvm.github.io/Kodistubs/_autosummary/xbmc.html?highlight=locale#xbmc.convertLanguage)?

Also, I´d like not to set this for the plugin especially. Haven't found it right away, but I think that there should be a way to get the preferred playback language set from within Kodi itself?! At least that would be the way I prefer. It also wouldn't break service asddons like [this one](https://forum.kodi.tv/showthread.php?tid=153783)

**Comment by GTechAlpha** [comment]
@asciidisco 
I did not want to include the huge list but I found no other way. :-)
NX requires a language-country code like 'de-DE' (German-Germany). All of the Kodi stuff works with language only. I did include a check for Kodi's value but it must conform to NX requirements, and it does not, currently.

**Comment by asciidisco** [comment]
@GTechAlpha I have an idea, will sketch out something (most probably over the weekend) that we can discuss. It´s just a lot of code to spit out a 5 char string :D

**Comment by GTechAlpha** [comment]
@asciidisco 
>It´s just a lot of code to spit out a 5 char string

I agree. A simpler alternative would be better.  :-)

**Comment by hawkeyexp** [comment]
@GTechAlpha @asciidisco 
if i understand it right you need a soltion to identify the system lang as "de-de" for example right ?
It is easy:
lang = xbmc.getLanguage(xbmc.ISO_639_1,True) - it will get country and region so we have the needed syntax :-)

**Comment by asciidisco** [comment]
@hawkeye Guve it a try with a few combinations, it’s broken (at least in my Kodi build) & does not return something useful.

But I do have another plan to realize this. I’m just to tired now to explain :D

**Comment by hawkeyexp** [comment]
tested on my win build and with my librelec in pi and both ggave me the result de-de ...

**Comment by asciidisco** [comment]
I´d propose something like this:

```python
import xbmc

DEFAULT_ISO_LOCALE = 'en-gb'

@classmethod
def __check_locale(cls, locale=''):
    if locale is None:
        return False
    if len(locale) < 5:
        return False
    return True

def get_iso_language(self):
    # fetch user setting & validate
    user_locale = self.settings.get(key='iso_locale')
    if self.__check_locale(locale=user_locale) is True:
        return user_locale
    # fetch kodi setting & validate
    iso_locale = ''
    iso_locale = xbmc.getLanguage(
        format=xbmc.ISO_639_1,
        region=True)
    if self.__check_locale(iso_locale) is False:
        # try to get the default locale from the gettext file
        iso_locale = self.get_local_string(string_id=30063)
        if self.__check_locale(iso_locale) is False:
            # if gettext locale is false as well, default to constant
            iso_locale = DEFAULT_ISO_LOCALE
    # persist the current setting
    self.settings.set(key='iso_locale', value=iso_locale)
    return iso_locale
```

Where in the gettext file the entry would look like this:

```
msgctxt "#30062"
msgid "locale"
msgstr "en-gb"
```

The user gets a 5 char textfield in the settings where they can change the locale manually if needed & we have a proper fallback chain to determine it locally.

Thoughts?

**Comment by hawkeyexp** [comment]
qasciidisco looks good to me

**Comment by pinoelefante** [comment]
in this way, do you get the region language?
ex: i have english as gui language but i live in italy and want it-IT.
if yes, it's good. if no, it's a first step 😃 
(The pains of a worldwide plugin xD)

**Comment by asciidisco** [comment]
@pinoelefante With the proposed solution, you could just simply go to the plugin settings (as there would be a textfield) & enter "it-it" in it. If the string you entered is syntactically valid, it wouldn't be overridden by the system.

**Comment by GTechAlpha** [comment]
The differences, as I understand them:

* The proposed change would require the user to recognize there is a problem, then figure out that this setting relates to the problem, then figure out what their locale code should be.

* The PR prompts the user to select a locale on first run and provides a list of language-country combinations to select from. This at the expense of making the plugin slightly larger.

Additionally, this issue isn't just about the default language. I have experienced a complete inability (temporary) to watch videos as a result of the locale being wrong.

**Comment by asciidisco** [comment]
@GTechAlpha I agree with your points. Maybe we both looked at it from the wrong side of the table.
If thought, if anyone should now which locale is the valid one for the user, then it should be Netflix.
A super quick evaluation showed that, amongst the data the plugin is already parsing, you can find this:

```
"SOMECRYPTICUSERID":{"avatar":["avatars","nf","icon36"],"precacheConfig":[],"summary":{"size":214,"\x24size":214,"\x24type":"leaf","maturityLevel":"OLDER_KIDS","language":"de-DE","isKids":true,"canEditCharacter":true,"avatarName":"icon36","experience":"jfk","isActive":false,"isAccountOwner":false,"guid":"SOMECRYPTICUSERID","profileName":"Kids"}
```

Especially:

```
"language":"de-DE"
```

Which totally makes sense, cause you can set different locale preferences for each user profile.
Fetching that piece of data (and reusing it) could be implemented pretty quick/easily.

What´s your opinion?

**Comment by GTechAlpha** [comment]
@asciidisco Of course, lol! Why didn't I think of that before. Makes perfect sense. Right there on the profile page:

``{"constants":{"sessionLength":[REMOVED],"ownerToken":[REMOVED],"locale":"en-US"``

Great, no need for any of this!

**Comment by asciidisco** [comment]
@GTechAlpha :D 
Collaborative coding FTW ;)

We might really need a place where we talk about implementations & *things* that need/should be done... ... ...any recommendations on how/where that could be done would be appreciated.

In regards to that @hawkeyexp sorry for not mailing you so far, had quite a stressful day, will write you when the little one is in bed.

**Comment by hawkeyexp** [comment]
@asciidisco no problem - you are right we need a place - my part ist most time small things but they must be done, too and some small are a big one, too :-)

**Comment by GTechAlpha** [comment]
Closing this since a better solution has been formulated.

**Pull request closed without merging**
