### PR TITLE
attempt to solve problem with video list ids being out of sync

### PR DESCRIPTION
**Pull request by im85288**
when stored as a widget and accessed at a later date

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by im85288** [comment]
@asciidisco  Sorry the second commit was not meant to come into this PR. It adds a retry decorator which I used to fix: https://github.com/asciidisco/plugin.video.netflix/issues/196 

I hope that does not cause too much issues and they can be reviewed together.

**Comment by im85288** [comment]
@hawkeyexp - If you get a chance please try and review this PR. Cheers :)

**Comment by hawkeyexp** [comment]
I'm trying out now :-) But i noticed we will get a merge conflict if gtechalpha's pr will me merged.

**Comment by asciidisco** [comment]
@hawkeyexp Please do not merge it now.

**Comment by im85288** [comment]
Thanks, yeah that was my fear when left for too long a period...the changes are not too complicated though so should be easy enough to merge or I can resubmit based on gtechalpha's PR once completed

**Comment by hawkeyexp** [comment]
@asciidisco merging is your part of work *lol* - i will only merge small things/fixes -no big code related stuff :-)

**Comment by im85288** [comment]
Thanks @hawkeyexp it’s my most used feature as I like to have my next up list on the home screen. @asciidisco if you want to merge the conflicts that’s fine or let me know if you’d like me to resubmit after you pull in the other PR. Cheers

**Comment by asciidisco** [comment]
@im85288 I´m going to merge some big chunk of refactored code most probably on Sunday, going to merge your PR during that merge session as well. Sorry for the delay.

**Comment by im85288** [comment]
Thanks @asciidisco - hopefully it should be straight forward but let me know if there’s anything confusing

**Comment by im85288** [comment]
@asciidisco - I attempted to merge these changes with master but now it does not seem to work. Has there been changes with regards caching the List ID used? Is this something I should try on the refactor branch instead as something has definitely changed. Thanks

**Comment by im85288** [comment]
It turns out this was down to it picking out the incorrect user when auto login is enabled (my last test was with only one user). The above change assures the profile is set at the start for all routing calls and prevents it from being called each time the addon is opened to show the user list/genres etc

**Comment by im85288** [comment]
@asciidisco - what's happening with this PR?

**Comment by caphm** [comment]
This can be closed, as it has been implemented in #300

**Comment by caphm** [comment]
Has been implemented in #300

**Pull request closed without merging**
