### PR TITLE
Expand search

### PR DESCRIPTION
**Pull request by GTechAlpha**
Performance impact is minimal, IMO.  See commits.

 **Expand search:**
- Split video information requests (if needed)
- Utilize NX Search API v2
- Add dynamic dictionary class
- Add service POST handling
- Add KodiDirectoryBuilder class
- Add persistent cache
- Add suggestions sub-listing

### CODE REVIEW

**Comment by hawkeyexp** [comment]
I have tested it and noticed sometimes timouts if result page is loaded and you scroll down and try to load next page.

**Comment by GTechAlpha** [comment]
@hawkeyexp Assuming we are on the same page, I have a solution to the issue and will add to PR tomorrow.

**Comment by GTechAlpha** [comment]
FYI - I am working on expanding and updating the search functionality to utilize NX searchAPIV2. I will update this PR when complete.

**Comment by asciidisco** [comment]
I was going to suggest that :)
Thank you for your help. Maybe this will also help us to fix https://github.com/asciidisco/plugin.video.netflix/issues/40

**Comment by GTechAlpha** [comment]
Glad to contribute :)

**Comment by hawkeyexp** [comment]
@GTechAlpha

can you please rework your pr to fix merge conflicts please?

**Comment by asciidisco** [comment]
@GTechAlpha @hawkeyexp I´ve adapted the search to the new API, reduced to one request (it really gained some speed now).
Thanks to the new Netflix API, the 413 status code error doesn't seem to be a problem anymore.
Also, all my searches with keywords ("star trek", "marvel", "wild") returned the same results as on the Netflix website.

**Comment by GTechAlpha** [comment]
@asciidisco I just updated the PR with my completed work.

**Comment by hawkeyexp** [comment]
I tested the new commit and noticed some bugs  inside suggestions like `Error Contents: local variable 'ref_from' referenced before assignment`. But i like the option for suggestions inside search result. Also artwork is missing inside suggestions only plain folder icons are shown. Possible you can set the netflix icon for genre's like on main menu and for videos the movie artwork which will result in a good looking menu.

**Comment by GTechAlpha** [comment]
Fixed the missing `ref_from` declaration.

**Comment by hawkeyexp** [comment]
@GTechAlpha 
I'm sorry but latest commit kills all - `Error Contents: maximum recursion depth exceeded`
i recommend a deeper testing...

**Comment by GTechAlpha** [comment]
@hawkeyexp That was due to a minor untested change that should not have been committed. Should be good now.

**Comment by hawkeyexp** [comment]
ok this bug is solved but i noticed a cunfusing thing:
for example search for "star trek" it results in the tvshows like discovery enterprise etc.
If i open suggestions it shows the movies (video) and an item (genre). If i select for example star trek nemesis (video) it shows again the main search result with the shows and the folder suggestion. I think this is not the wanted behaviour :-)

**Comment by GTechAlpha** [comment]
@hawkeyexp When I follow your example exactly (search star trek > go to SUGGESTIONS > select Star Trek: Nemesis (video)), I get the expected results for Star Trek: Nemesis.

**Comment by asciidisco** [comment]
Haven't had time to test your PR, but it is rather huge. Will try to take some time to review it accordingly. Hope you don't mind that.

**Comment by GTechAlpha** [comment]
@asciidisco Not at all.

**Comment by GTechAlpha** [comment]
@hawkeyexp Correction from my previous comment about the suggestion/entity artwork: there is entity artwork available.

**Comment by GTechAlpha** [comment]
> ok this bug is solved but i noticed a cunfusing thing:
for example search for "star trek" it results in the tvshows like discovery enterprise etc.
If i open suggestions it shows the movies (video) and an item (genre). If i select for example star trek nemesis (video) it shows again the main search result with the shows and the folder suggestion. I think this is not the wanted behaviour :-)

@hawkeyexp After some thought, I think the issue you are experiencing is due to caching (memcache) -- I have it disabled. Will investigate tomorrow.

**Comment by hawkeyexp** [comment]
@GTechAlpha in confirm it seems cache related :-) I send you a PR with some tweaks to extend your pr with art and fixed a small bug.

**Comment by hawkeyexp** [comment]
@GTechAlpha 
i have noticed a last thing realted to seach cache :-(
1) do a search for example for "star trek" - you will get the search result
2) go back tro main menu
3) start new search for example "schwarzenegger" - you will get the response from start trek :-(

By the way: have you found a way to set the fanart as i showed you in the pr ?

**Comment by GTechAlpha** [comment]
Caching fixed with latest commit.

**Comment by hawkeyexp** [comment]
dont't understand me wrong - the only missing part is the default fanart image from addon (netflix-logo) set on the folder suggestions and the items inside the solve blank items when skin is in fanart view :-)

**Comment by GTechAlpha** [comment]
@hawkeyexp 
I merged your PR earlier, so it's there now?

**Comment by hawkeyexp** [comment]
No as i have written i dind't find the working way to set it inside your complexer code :-(

But rest looks good now and is working fine and fanart is only cosmetic - so it can be fixed later.

**Comment by GTechAlpha** [comment]
Turns out that my original statement was correct:
>The suggestions are classified as entities and behave like sub-searches. They do not have artwork of their own.

I saw something that made me think otherwise, but no.

**Comment by GTechAlpha** [comment]
@hawkeyexp Sorry for the misunderstanding. Added with latest commit.

**Comment by hawkeyexp** [comment]
> @hawkeyexp Sorry for the misunderstanding. Added with latest commit.
@GTechAlpha no problem :-) Art is now working perfect!
After merge i will fix setview - it seems it is in some parts not set or ignored.

**Comment by GTechAlpha** [comment]
Latest commit should be the final commit on this PR. I think everything is good now.

**Comment by hawkeyexp** [comment]
@GTechAlpha i know you will not be happy but can you have a look to setview cause next days i have to move last things from my old apartment to new one and will be only online via mobile. Setview inside some folders are broken.
For example:
mylist is shown as view folder - should be movie - entering a show inside mylist is working fine and shown as view show also seasons and episodes are ok. Same behaviour in other parts like genre and search results. Would be great and if you can have a look on it - will fully complete the pr.

**Comment by GTechAlpha** [comment]
@hawkeyexp Wasn't sure what you meant before because I don't use custom views. Last commit should fix it.

**Comment by hawkeyexp** [comment]
@gtechalpha - great looks gold to me but can't test it before saturday.
@asciidisco if you can check if code is now fully working merge it :-)

**Pull request closed without merging**
